version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    container_name: sqlserver
  app:
    build:
      context: ./DatabaseFirst
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=YourDb;User Id=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - sqlserver
    ports:
      - "8080:80"